### PR TITLE
Refs #163 return localization row timestamp from the db to the client

### PR DESCRIPTION
**Pull request by bliles**

### CODE REVIEW

**Comment by RickStrahl** [comment]
Why do we want this?

**Comment by bliles** [comment]
Originally I thought I wanted accurate timestamps as I was working on adding the ability to flag a translation as out of date, however, I don't really need the information here as you've observed.

I will say that without this change, the API returns inaccurate information since it includes an Updated property in the response, but the value of the property is always the timestamp when the request was processed by the API and not the actual value from the DB. So just for accuracy I would think you'd either want to not have an Updated property in the api response, or it should be accurate.

**Comment by RickStrahl** [comment]
Good point. Not sure where the invalid value is coming from. I'm assuming it's just going back to the client because of the raw serialization. But why the value would be different than what is in the actual record I'm not sure.

**Comment by bliles** [comment]
Since ResourceItemEx extends ResourceItem, it's getting a new timestamp because you're creating a new instance of the object. On line 144 of DbResourceManager/ResourceItem.cs _Updated is initialized to DateTime.UtcNow.

**Comment by RickStrahl** [comment]
Merging, given that it's going down to the client now, at least it will be accurate :-)

Thanks.

**Pull request merged**
